language: php
sudo: false
php:
  - "5.3"
matrix:
  include:
    - php: 5.3
      dist: precise
script:
  - php build.php
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOYTOKEN
  target-branch: release
  local-dir: dist
  on:
    branch: master